// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zadcvpasrnubowznoytv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphZGN2cGFzcm51Ym93em5veXR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MzU1OTgsImV4cCI6MjA2MzUxMTU5OH0.RW7l60Wi2xKGq551jjB_dBXd1qwQNlGNT_hA32p7xRA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);